### ISSUE TITLE
Job listing should be a bit more descriptive

### ISSUE THREAD

**Issue by jeremiak** [mnylc/metro.org#14]
The job listing view should have the following items for each job posting:
1. Title of the job
2. Place
3. Description of the position

The listing does not need any search or filter to start, but we can always add that in if we think it will be helpful.

**Comment by natehill** [comment]
@jeremiak we are working on a google form for this so that members can input the info themselves.  @daviserinanderson is on it.  do you know of any nifty ways to automate going from google sheets to markdown?  A quick google suggests there are some toys to play with...
