### ISSUE TITLE
Investigate using a photo from Metro archives

### ISSUE THREAD

**Issue by jeremiak** [mnylc/metro.org#16]
The background image looks great, but Metro apparently has a nice archive of photos and it would be great to use one of Metro's images if possible.

@natehill could you point me in the direction of the archive or some photos you think would be a good starting place?

**Comment by natehill** [comment]
dig on some of these- http://dcmny.org/

**Comment by jeremiak** [comment]
Found a few that initially stood out as good candidates:
* [Brooklyn Bridge and the East River, New York City, 1924. Roege 9306](http://dcmny.org/islandora/object/photosnycbeyond%3A23567)
* [34th Street from 8th Avenue looking east towards the Empire State Building](http://www.dcmny.org/islandora/object/cuny34thstreet%3A851)
* [The Top of New York: Empire State Building Observatory Pierces the Clouds, 1250 Feet High](http://www.dcmny.org/islandora/object/cuny34thstreet%3A867)
* [Yankee Stadium](http://dcmny.org/islandora/object/bronxbusiness%3A82)

Going to try out the shot of the Empire State building to start. Feel free at add other links of good images you know of @natehill
