### ISSUE TITLE
too much damn content to add :(

### ISSUE THREAD

**Issue by natehill** [mnylc/metro.org#20]
Ugh.  Converting all these job listings to markdown is killing me @jeremiak - and I have other edits that require more thought and wordsmithing as well.  I may not make this deadline.  Will submit a pull request when I've got more there.  Sigh.

**Comment by jeremiak** [comment]
Hey @natehill feel free to stop where you are and go ahead and add my email address to the spreadsheet and I'll see if I can get something more automated together.
